spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: AUTH-SERVICE
          uri: http://72.60.234.52:8091
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - id: ADMIN-SERVICE
          uri: http://10.110.10.46:8688
          predicates:
            - Path=/api/v1/auto-test-web/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: AuthFilter
        - id: RENTINO-SERVICE
          uri: http://72.60.234.52:8090
          predicates:
            - Path=/api/v1/rentino/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      httpclient:
        connect-timeout: 120000
        response-timeout: 600s
        pool:
          max-idle-time: 600s
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8888

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    disable-swagger-default-url: true
    path: swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /api/v1/auth/v3/api-docs
        name: AUTH SERVICE
      - url: /api/v1/rentino/v3/api-docs
        name: RENTINO SERVICE